services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fecaf
    volumes:
      - fecaf_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: fecaf
    depends_on:
      - db
    entrypoint: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "30s", "node", "index.js"]

volumes:
  fecaf_data: