USE fecaf;

CREATE TABLE IF NOT EXISTS alunos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    curso VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(255) NOT NULL,
    matricula INT NOT NULL UNIQUE
);

INSERT INTO fecaf.alunos (
    nome,
    curso,
    avatar_url,
    matricula
) VALUES 
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('John Doe', 'Análise e Desenvolvimento de Sistemas', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Jane Smith', 'Logística', 'https://i.pravatar.cc', FLOOR(RAND()*100000)),
('Alice Johnson', 'Automação Industrial', 'https://i.pravatar.cc', FLOOR(RAND()*100000));
